name: Check base branch
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            if (context.payload.pull_request.base.ref === 'main') {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: '⚠️ The base branch of this Pull Request is `main`. Please confirm!'
              });
            }
