name: Pull request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  # check-import:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [ 18.x ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: |
  #         npx eslint .

  check-pr-vlidation:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          if [[ ! $PR_TITLE =~ \#[[:alnum:][:punct:]]+$ ]]; then
            echo "PR title does not meet the condition"
            exit 1
          fi
        shell: bash

      - name: Check PR label
        run: |
          PR_LABELS_JSON=${{ toJson(github.event.pull_request.labels) }}
          LABEL_COUNT=$(echo "$PR_LABELS_JSON" | jq '. | length')
          echo "Number of PR labels: $LABEL_COUNT"
          if [[ $LABEL_COUNT -eq 0 ]]; then
            echo "PR does not have any labels"
            exit 1
          fi
        shell: bash

      - name: Check PR milestone
        run: |
          PR_MILESTONE="${{ github.event.pull_request.milestone }}"
          if [ -z "$PR_MILESTONE" ]; then
            echo "PR does not have a milestone"
            exit 1
          else
            echo "PR milestone: $PR_MILESTONE"
          fi
        shell: bash



