name: Pull request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-import:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npx eslint .

  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          # Check if PR title has # followed by any character
          if [[ ! $PR_TITLE =~ #[\w\W]+$ ]]; then
            echo "PR title does not meet the condition"
            exit 1
          fi
        shell: bash



